dbt_model:
  outputs:
    dev:
      dbname: postgres
      host: postgres
      pass: airairflow
      port: 5432
      schema: public
      threads: 4
      type: postgres
      user: airflow
  target: dev
